from decouple import config

KAFKA_BOOTSTRAP_SERVERS = '#'
PLAYER_SERVICE_URL = config("PLAYER_SERVICE_URL")
MATCH_SERVICE_URL = config("MATCH_SERVICE_URL")
JWT_SERVICE_PUBLIC_KEY = config("JWT_SERVICE_PUBLIC_KEY")

BOOTSTRAP_SERVER_RUNNING = config("BOOTSTRAP_SERVER_RUNNING")
KAFKA_GROUP_ID = config("KAFKA_GROUP_ID")

class Config:
    SQLALCHEMY_DATABASE_URI = config("SQLALCHEMY_DATABASE_URI")
    SECRET_KEY = config("SECRET_KEY")
    SQLALCHEMY_TRACK_MODIFICATIONS = config("SQLALCHEMY_TRACK_MODIFICATIONS")

class TestConfig(Config):
    TESTING = config("TESTING")
    TESTING_SQLALCHEMY_DATABASE_URI = config("TESTING_SQLALCHEMY_DATABASE_URI")
    TESTING_SQLALCHEMY_TRACK_MODIFICATIONS = config("SQLALCHEMY_TRACK_MODIFICATIONS")